name: dask-examples
channels:
  - conda-forge
dependencies:
  # Environment dependencies
  - python=3.9
  - pip
  # Dask dependencies
  - dask=2022.1.1
  - dask-image=2021.12.0
  - dask-ml=2022.1.22
  # Other pinned dependencies
  - numpy=1.21
  - pandas=1.3
  # Dependencies for the examples
  - numba
  - bokeh
  - pyarrow
  - python-graphviz
  - seaborn
  - scikit-learn
  - scikit-image
  - matplotlib
  - h5py
  - xarray
  - pooch
  - bottleneck
  - requests
  # Dependencies to build the site
  - pandoc
  - nbconvert
  - nbformat
  - jupyter_client
  - ipykernel
  - nbsphinx
  - dask-sphinx-theme>=2
  - sphinx
  - nbmake
  - pytest-xdist
  # Special case for prophet. Copied from their requirements.txt file
  - cmdstanpy==0.9.68 # this does not bring cmdstan with it
  - convertdate
  - holidays
  - Cython
  - python-dateutil
  - tqdm
  - pip:
      - lunarcalendar
      - mimesis
      - xgboost
